"""nullable

Revision ID: 03971bce8f1f
Revises: 08c391b32c7c
Create Date: 2024-05-14 11:17:57.231339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03971bce8f1f'
down_revision = '08c391b32c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('sequential_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('login',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('type_',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('crm_1c_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('telephony_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('deleted_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('patronymic',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('parameters',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('parameters',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('patronymic',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('deleted_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('telephony_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('crm_1c_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('type_',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('login',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('sequential_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
