"""basic

Revision ID: 476f1d8cf250
Revises: 
Create Date: 2024-05-07 17:17:07.985425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476f1d8cf250'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequential_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_entity_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('agreement_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('work_type_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=False),
    sa.Column('employees_updated_at', sa.DateTime(), nullable=False),
    sa.Column('contacts_updated_at', sa.DateTime(), nullable=False),
    sa.Column('delay_to', sa.DateTime(), nullable=False),
    sa.Column('spent_time_total', sa.Float(), nullable=False),
    sa.Column('start_execution_until', sa.DateTime(), nullable=False),
    sa.Column('planned_execution_in_hours', sa.Float(), nullable=False),
    sa.Column('planned_reaction_at', sa.DateTime(), nullable=False),
    sa.Column('reacted_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('spent_seconds_for_reaction_in_sla', sa.Integer(), nullable=False),
    sa.Column('spent_seconds_for_completion_in_sla', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('sequential_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('type_', sa.String(), nullable=False),
    sa.Column('crm_1c_id', sa.String(), nullable=False),
    sa.Column('telephony_number', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=300), nullable=False),
    sa.Column('patronymic', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('issues')
    # ### end Alembic commands ###
