"""user issue

Revision ID: 558d95772cb2
Revises: 476f1d8cf250
Create Date: 2024-05-13 16:35:39.181212

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "558d95772cb2"
down_revision = "476f1d8cf250"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.alter_column("contact_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("assignee_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("author_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("parent_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.create_foreign_key(
            "fk_author_id_users", "users", ["author_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_contact_id_users", "users", ["contact_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_assignee_id_users", "users", ["assignee_id"], ["id"]
        )
        batch_op.drop_column("title")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint("fk_author_id_users", type_="foreignkey")
        batch_op.drop_constraint("fk_contact_id_users", type_="foreignkey")
        batch_op.drop_constraint("fk_assignee_id_users", type_="foreignkey")

        batch_op.alter_column("parent_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("author_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("assignee_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("contact_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
